AWSTemplateFormatVersion: '2010-09-09'
Description: 'Claude Code with Bedrock - Cognito User Pool Authentication Stack'

Parameters:
  FederationType:
    Type: String
    Default: direct
    AllowedValues:
      - direct
      - cognito
    Description: Authentication mode - Direct IAM or Cognito Identity Pool

  CognitoUserPoolId:
    Type: String
    Description: Existing Cognito User Pool ID (e.g., us-west-2_ABC123DEF)
    AllowedPattern: '^[\w-]+_[0-9a-zA-Z]+$'
    ConstraintDescription: Must be a valid Cognito User Pool ID

  CognitoUserPoolClientId:
    Type: String
    Description: Cognito User Pool App Client ID
    AllowedPattern: '^[a-z0-9]{26}$'
    ConstraintDescription: Must be a valid Cognito User Pool Client ID

  CognitoUserPoolDomain:
    Type: String
    Description: Cognito User Pool domain (without .auth.region.amazoncognito.com)
    AllowedPattern: '^[a-z0-9](?:[a-z0-9\-]{0,61}[a-z0-9])?$'
    ConstraintDescription: Must be a valid Cognito domain prefix

  IdentityPoolName:
    Type: String
    Default: claude-code-cognito
    Description: Name for the Cognito Identity Pool
    AllowedPattern: '^[\w\s+=,.@-]+$'
    MaxLength: 128

  FederatedRoleName:
    Type: String
    Default: BedrockCognitoFederatedRole
    Description: Name for the IAM role used for federation
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9-_]*$'
    MaxLength: 64

  AllowedBedrockRegions:
    Type: CommaDelimitedList
    Default: 'us-east-1,us-west-2'
    Description: Comma-delimited list of AWS regions where Bedrock access is allowed

  EnableMonitoring:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable CloudWatch monitoring for Bedrock usage

Conditions:
  UseDirectIAM: !Equals [!Ref FederationType, direct]
  UseCognitoIdentity: !Equals [!Ref FederationType, cognito]
  MonitoringEnabled: !Equals [!Ref EnableMonitoring, 'true']

Resources:
  # ===============================================
  # OIDC Provider for Cognito User Pool
  # ===============================================

  CognitoUserPoolOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Condition: UseDirectIAM
    Properties:
      Url: !Sub 'https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPoolId}'
      ClientIdList:
        - !Ref CognitoUserPoolClientId
      ThumbprintList:
        - 9e99a48a9960b14926bb7f3b02e22da2b0ab7280  # AWS Cognito thumbprint
      Tags:
        - Key: Purpose
          Value: Claude Code Cognito User Pool Authentication
        - Key: Provider
          Value: CognitoUserPool

  # ===============================================
  # Bedrock Access Policy (Shared)
  # ===============================================

  BedrockAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for accessing Bedrock services
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowBedrockInvokeRegional
            Effect: Allow
            Action:
              - 'bedrock:InvokeModel'
              - 'bedrock:InvokeModelWithResponseStream'
              - 'bedrock-runtime:InvokeModel'
              - 'bedrock-runtime:InvokeModelWithResponseStream'
              - 'bedrock-runtime:ConverseStream'
              - 'bedrock-runtime:Converse'
            Resource:
              - 'arn:aws:bedrock:*::foundation-model/*'
              - 'arn:aws:bedrock:*:*:inference-profile/*'
            Condition:
              StringEquals:
                'aws:RequestedRegion': !Ref AllowedBedrockRegions
          - Sid: AllowBedrockInvokeGlobal
            Effect: Allow
            Action:
              - 'bedrock:InvokeModel'
              - 'bedrock:InvokeModelWithResponseStream'
              - 'bedrock-runtime:InvokeModel'
              - 'bedrock-runtime:InvokeModelWithResponseStream'
              - 'bedrock-runtime:ConverseStream'
              - 'bedrock-runtime:Converse'
            Resource:
              - 'arn:aws:bedrock:::foundation-model/*'
          - Sid: AllowBedrockListRegional
            Effect: Allow
            Action:
              - 'bedrock:ListFoundationModels'
              - 'bedrock:GetFoundationModel'
              - 'bedrock:GetFoundationModelAvailability'
              - 'bedrock:ListInferenceProfiles'
              - 'bedrock:GetInferenceProfile'
            Resource:
              - 'arn:aws:bedrock:*::foundation-model/*'
              - 'arn:aws:bedrock:*:*:inference-profile/*'
            Condition:
              StringEquals:
                'aws:RequestedRegion': !Ref AllowedBedrockRegions
          - Sid: AllowBedrockListGlobal
            Effect: Allow
            Action:
              - 'bedrock:ListFoundationModels'
              - 'bedrock:GetFoundationModel'
              - 'bedrock:GetFoundationModelAvailability'
              - 'bedrock:ListInferenceProfiles'
              - 'bedrock:GetInferenceProfile'
            Resource:
              - 'arn:aws:bedrock:::foundation-model/*'
          - !If
            - MonitoringEnabled
            - Sid: AllowCloudWatchMetrics
              Effect: Allow
              Action:
                - 'cloudwatch:PutMetricData'
              Resource: '*'
              Condition:
                StringEquals:
                  'cloudwatch:namespace':
                    - 'ClaudeCode/Bedrock/Usage'
                    - 'AWS/Bedrock'
            - !Ref 'AWS::NoValue'

  # ===============================================
  # Direct IAM Resources (when FederationType=direct)
  # ===============================================

  DirectIAMRole:
    Type: AWS::IAM::Role
    Condition: UseDirectIAM
    Properties:
      RoleName: !Ref FederatedRoleName
      Description: Direct IAM role for Cognito User Pool users accessing Bedrock
      MaxSessionDuration: 43200  # 12 hours
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !GetAtt CognitoUserPoolOIDCProvider.Arn
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
              - 'sts:TagSession'
      ManagedPolicyArns:
        - !Ref BedrockAccessPolicy
      Tags:
        - Key: Purpose
          Value: Claude Code Direct IAM Authentication
        - Key: Provider
          Value: CognitoUserPool
        - Key: FederationType
          Value: direct

  # ===============================================
  # Cognito Identity Pool Resources (when FederationType=cognito)
  # ===============================================

  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Condition: UseCognitoIdentity
    Properties:
      IdentityPoolName: !Ref IdentityPoolName
      AllowUnauthenticatedIdentities: false
      AllowClassicFlow: false
      CognitoIdentityProviders:
        - ClientId: !Ref CognitoUserPoolClientId
          ProviderName: !Sub 'cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPoolId}'
          ServerSideTokenCheck: true

  CognitoAuthenticatedRole:
    Type: AWS::IAM::Role
    Condition: UseCognitoIdentity
    Properties:
      Description: Role for authenticated Cognito Identity Pool users
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
              - 'sts:TagSession'
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud': !Ref CognitoIdentityPool
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': authenticated
      ManagedPolicyArns:
        - !Ref BedrockAccessPolicy
      Tags:
        - Key: Purpose
          Value: Claude Code Cognito Authentication
        - Key: Provider
          Value: CognitoUserPool

  CognitoUnauthenticatedRole:
    Type: AWS::IAM::Role
    Condition: UseCognitoIdentity
    Properties:
      Description: Role for unauthenticated Cognito Identity Pool users (restricted)
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud': !Ref CognitoIdentityPool
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': unauthenticated
      Policies:
        - PolicyName: DenyAll
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Deny
                Action: '*'
                Resource: '*'
      Tags:
        - Key: Purpose
          Value: Claude Code Cognito Unauthenticated Role
        - Key: Provider
          Value: CognitoUserPool

  CognitoIdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Condition: UseCognitoIdentity
    Properties:
      IdentityPoolId: !Ref CognitoIdentityPool
      Roles:
        authenticated: !GetAtt CognitoAuthenticatedRole.Arn
        unauthenticated: !GetAtt CognitoUnauthenticatedRole.Arn

  # Principal Tag Mapping for Session Tags
  IdentityPoolPrincipalTag:
    Type: AWS::Cognito::IdentityPoolPrincipalTag
    Condition: UseCognitoIdentity
    DeletionPolicy: Delete
    Properties:
      IdentityPoolId: !Ref CognitoIdentityPool
      IdentityProviderName: !Sub 'cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPoolId}'
      UseDefaults: false
      PrincipalTags:
        UserEmail: email
        UserId: sub

  # ===============================================
  # Optional Monitoring Resources
  # ===============================================

  BedrockAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Condition: MonitoringEnabled
    Properties:
      LogGroupName: !Sub '/aws/bedrock/claude-code-${AWS::StackName}'
      RetentionInDays: 30

Outputs:
  FederationType:
    Description: Current federation type configuration
    Value: !Ref FederationType
    Export:
      Name: !Sub '${AWS::StackName}-FederationType'

  OIDCProviderArn:
    Description: ARN of the Cognito User Pool OIDC Provider
    Condition: UseDirectIAM
    Value: !GetAtt CognitoUserPoolOIDCProvider.Arn
    Export:
      Name: !Sub '${AWS::StackName}-OIDCProviderArn'

  FederatedRoleArn:
    Description: ARN of the federated role for Cognito User Pool users
    Value: !If
      - UseDirectIAM
      - !GetAtt DirectIAMRole.Arn
      - !GetAtt CognitoAuthenticatedRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FederatedRoleArn'

  DirectSTSRoleArn:
    Description: Direct STS federated role ARN (when using direct IAM)
    Condition: UseDirectIAM
    Value: !GetAtt DirectIAMRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-DirectSTSRoleArn'

  BedrockRoleArn:
    Description: IAM Role ARN for Bedrock access (for backward compatibility)
    Value: !If
      - UseDirectIAM
      - !GetAtt DirectIAMRole.Arn
      - !GetAtt CognitoAuthenticatedRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BedrockRoleArn'

  IdentityPoolId:
    Description: Cognito Identity Pool ID
    Condition: UseCognitoIdentity
    Value: !Ref CognitoIdentityPool
    Export:
      Name: !Sub '${AWS::StackName}-IdentityPoolId'

  BedrockPolicyArn:
    Description: ARN of the Bedrock access policy
    Value: !Ref BedrockAccessPolicy
    Export:
      Name: !Sub '${AWS::StackName}-BedrockPolicyArn'

  ConfigurationJson:
    Description: Configuration JSON for CLI tool
    Value: !If
      - UseDirectIAM
      - !Sub |
        {
          "federation_type": "direct",
          "provider_type": "cognito",
          "cognito_user_pool_id": "${CognitoUserPoolId}",
          "cognito_domain": "${CognitoUserPoolDomain}",
          "client_id": "${CognitoUserPoolClientId}",
          "federated_role_arn": "${DirectIAMRole.Arn}",
          "aws_region": "${AWS::Region}",
          "max_session_duration": 43200
        }
      - !Sub |
        {
          "federation_type": "cognito",
          "provider_type": "cognito",
          "cognito_user_pool_id": "${CognitoUserPoolId}",
          "cognito_domain": "${CognitoUserPoolDomain}",
          "client_id": "${CognitoUserPoolClientId}",
          "identity_pool_id": "${CognitoIdentityPool}",
          "federated_role_arn": "${CognitoAuthenticatedRole.Arn}",
          "aws_region": "${AWS::Region}"
        }
