AWSTemplateFormatVersion: '2010-09-09'
Description: 'Claude Code with Bedrock - Azure AD Authentication Stack'

Parameters:
  FederationType:
    Type: String
    Default: direct
    AllowedValues:
      - direct
      - cognito
    Description: Authentication mode - Direct IAM or Cognito Identity Pool

  AzureTenantId:
    Type: String
    Description: Your Azure AD tenant ID (GUID format)
    AllowedPattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
    ConstraintDescription: Must be a valid Azure tenant ID (GUID)

  AzureClientId:
    Type: String
    Description: Azure AD application (client) ID
    AllowedPattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
    ConstraintDescription: Must be a valid Azure client ID (GUID)

  IdentityPoolName:
    Type: String
    Default: claude-code-azure
    Description: Name for the Cognito Identity Pool (used in cognito mode)
    AllowedPattern: '^[\w\s+=,.@-]+$'
    MaxLength: 128

  FederatedRoleName:
    Type: String
    Default: BedrockAzureFederatedRole
    Description: Name for the IAM role used for federation
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9-_]*$'
    MaxLength: 64

  AllowedBedrockRegions:
    Type: CommaDelimitedList
    Default: 'us-east-1,us-west-2'
    Description: Comma-delimited list of AWS regions where Bedrock access is allowed

  EnableMonitoring:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable CloudWatch monitoring for Bedrock usage

Conditions:
  UseDirectIAM: !Equals [!Ref FederationType, direct]
  UseCognitoIdentity: !Equals [!Ref FederationType, cognito]
  MonitoringEnabled: !Equals [!Ref EnableMonitoring, 'true']

Resources:
  # ===============================================
  # OIDC Provider for Azure AD
  # ===============================================

  AzureOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: !Sub 'https://sts.windows.net/${AzureTenantId}/'
      ClientIdList:
        - !Ref AzureClientId
      ThumbprintList:
        - 626d44e704d1ceabe3bf0d53397464ac8080142c  # Microsoft Azure AD thumbprint
        - 3a6ee4abbc964291263d9268b89ffadc8dc2d107  # Additional Azure AD thumbprint
      Tags:
        - Key: Purpose
          Value: Claude Code Azure AD Authentication
        - Key: Provider
          Value: Azure

  # ===============================================
  # Bedrock Access Policy (Shared)
  # ===============================================

  BedrockAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for accessing Bedrock services
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowBedrockInvokeRegional
            Effect: Allow
            Action:
              - 'bedrock:InvokeModel'
              - 'bedrock:InvokeModelWithResponseStream'
              - 'bedrock-runtime:InvokeModel'
              - 'bedrock-runtime:InvokeModelWithResponseStream'
              - 'bedrock-runtime:ConverseStream'
              - 'bedrock-runtime:Converse'
            Resource:
              - 'arn:aws:bedrock:*::foundation-model/*'
              - 'arn:aws:bedrock:*:*:inference-profile/*'
            Condition:
              StringEquals:
                'aws:RequestedRegion': !Ref AllowedBedrockRegions
          - Sid: AllowBedrockInvokeGlobal
            Effect: Allow
            Action:
              - 'bedrock:InvokeModel'
              - 'bedrock:InvokeModelWithResponseStream'
              - 'bedrock-runtime:InvokeModel'
              - 'bedrock-runtime:InvokeModelWithResponseStream'
              - 'bedrock-runtime:ConverseStream'
              - 'bedrock-runtime:Converse'
            Resource:
              - 'arn:aws:bedrock:::foundation-model/*'
          - Sid: AllowBedrockListRegional
            Effect: Allow
            Action:
              - 'bedrock:ListFoundationModels'
              - 'bedrock:GetFoundationModel'
              - 'bedrock:GetFoundationModelAvailability'
              - 'bedrock:ListInferenceProfiles'
              - 'bedrock:GetInferenceProfile'
            Resource:
              - 'arn:aws:bedrock:*::foundation-model/*'
              - 'arn:aws:bedrock:*:*:inference-profile/*'
            Condition:
              StringEquals:
                'aws:RequestedRegion': !Ref AllowedBedrockRegions
          - Sid: AllowBedrockListGlobal
            Effect: Allow
            Action:
              - 'bedrock:ListFoundationModels'
              - 'bedrock:GetFoundationModel'
              - 'bedrock:GetFoundationModelAvailability'
              - 'bedrock:ListInferenceProfiles'
              - 'bedrock:GetInferenceProfile'
            Resource:
              - 'arn:aws:bedrock:::foundation-model/*'
          - !If
            - MonitoringEnabled
            - Sid: AllowCloudWatchMetrics
              Effect: Allow
              Action:
                - 'cloudwatch:PutMetricData'
              Resource: '*'
              Condition:
                StringEquals:
                  'cloudwatch:namespace':
                    - 'ClaudeCode/Bedrock/Usage'
                    - 'AWS/Bedrock'
            - !Ref 'AWS::NoValue'

  # ===============================================
  # Direct IAM Resources (when FederationType=direct)
  # ===============================================

  DirectIAMRole:
    Type: AWS::IAM::Role
    Condition: UseDirectIAM
    Properties:
      RoleName: !Ref FederatedRoleName
      Description: Direct IAM role for Azure AD users accessing Bedrock
      MaxSessionDuration: 43200  # 12 hours
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !GetAtt AzureOIDCProvider.Arn
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
              - 'sts:TagSession'
      ManagedPolicyArns:
        - !Ref BedrockAccessPolicy
      Tags:
        - Key: Purpose
          Value: Claude Code Direct IAM Authentication
        - Key: Provider
          Value: Azure
        - Key: FederationType
          Value: direct

  # ===============================================
  # Cognito Identity Pool Resources (when FederationType=cognito)
  # ===============================================

  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Condition: UseCognitoIdentity
    Properties:
      IdentityPoolName: !Ref IdentityPoolName
      AllowUnauthenticatedIdentities: false
      AllowClassicFlow: false
      OpenIdConnectProviderARNs:
        - !GetAtt AzureOIDCProvider.Arn

  CognitoAuthenticatedRole:
    Type: AWS::IAM::Role
    Condition: UseCognitoIdentity
    Properties:
      Description: Role for authenticated Cognito Identity Pool users
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud': !Ref CognitoIdentityPool
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': authenticated
      ManagedPolicyArns:
        - !Ref BedrockAccessPolicy
      Tags:
        - Key: Purpose
          Value: Claude Code Cognito Authentication
        - Key: Provider
          Value: Azure

  CognitoUnauthenticatedRole:
    Type: AWS::IAM::Role
    Condition: UseCognitoIdentity
    Properties:
      Description: Role for unauthenticated Cognito Identity Pool users (restricted)
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud': !Ref CognitoIdentityPool
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': unauthenticated
      Policies:
        - PolicyName: DenyAll
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Deny
                Action: '*'
                Resource: '*'
      Tags:
        - Key: Purpose
          Value: Claude Code Cognito Unauthenticated Role
        - Key: Provider
          Value: Azure

  CognitoIdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Condition: UseCognitoIdentity
    Properties:
      IdentityPoolId: !Ref CognitoIdentityPool
      Roles:
        authenticated: !GetAtt CognitoAuthenticatedRole.Arn
        unauthenticated: !GetAtt CognitoUnauthenticatedRole.Arn

  # Principal Tag Mapping for Session Tags
  IdentityPoolPrincipalTag:
    Type: AWS::Cognito::IdentityPoolPrincipalTag
    Condition: UseCognitoIdentity
    DeletionPolicy: Delete
    Properties:
      IdentityPoolId: !Ref CognitoIdentityPool
      IdentityProviderName: !Sub 'login.microsoftonline.com/${AzureTenantId}/v2.0'
      UseDefaults: false
      PrincipalTags:
        UserEmail: email
        UserId: sub
        UserName: name

  # ===============================================
  # Optional Monitoring Resources
  # ===============================================

  BedrockAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Condition: MonitoringEnabled
    Properties:
      LogGroupName: !Sub '/aws/bedrock/claude-code-${AWS::StackName}'
      RetentionInDays: 30

Outputs:
  FederationType:
    Description: Current federation type configuration
    Value: !Ref FederationType
    Export:
      Name: !Sub '${AWS::StackName}-FederationType'

  OIDCProviderArn:
    Description: ARN of the Azure AD OIDC Provider
    Value: !GetAtt AzureOIDCProvider.Arn
    Export:
      Name: !Sub '${AWS::StackName}-OIDCProviderArn'

  FederatedRoleArn:
    Description: ARN of the federated role for Azure AD users
    Value: !If
      - UseDirectIAM
      - !GetAtt DirectIAMRole.Arn
      - !GetAtt CognitoAuthenticatedRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FederatedRoleArn'

  DirectSTSRoleArn:
    Description: Direct STS federated role ARN (when using direct IAM)
    Condition: UseDirectIAM
    Value: !GetAtt DirectIAMRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-DirectSTSRoleArn'

  BedrockRoleArn:
    Description: IAM Role ARN for Bedrock access (for backward compatibility)
    Value: !If
      - UseDirectIAM
      - !GetAtt DirectIAMRole.Arn
      - !GetAtt CognitoAuthenticatedRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BedrockRoleArn'

  IdentityPoolId:
    Description: Cognito Identity Pool ID (if using Cognito mode)
    Condition: UseCognitoIdentity
    Value: !Ref CognitoIdentityPool
    Export:
      Name: !Sub '${AWS::StackName}-IdentityPoolId'

  BedrockPolicyArn:
    Description: ARN of the Bedrock access policy
    Value: !Ref BedrockAccessPolicy
    Export:
      Name: !Sub '${AWS::StackName}-BedrockPolicyArn'

  ConfigurationJson:
    Description: Configuration JSON for CLI tool
    Value: !If
      - UseDirectIAM
      - !Sub |
        {
          "federation_type": "direct",
          "provider_type": "azure",
          "azure_tenant_id": "${AzureTenantId}",
          "client_id": "${AzureClientId}",
          "federated_role_arn": "${DirectIAMRole.Arn}",
          "aws_region": "${AWS::Region}",
          "max_session_duration": 43200
        }
      - !Sub |
        {
          "federation_type": "cognito",
          "provider_type": "azure",
          "azure_tenant_id": "${AzureTenantId}",
          "client_id": "${AzureClientId}",
          "identity_pool_id": "${CognitoIdentityPool}",
          "federated_role_arn": "${CognitoAuthenticatedRole.Arn}",
          "aws_region": "${AWS::Region}"
        }
